//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiuQinSys.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentOrderMain
    {
        public string no { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> effectDate { get; set; }
        public string custID { get; set; }
        public string custName { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string invoiceaddr { get; set; }
        public Nullable<byte> taxRate { get; set; }
        public string remark { get; set; }
        public Nullable<byte> userSeq { get; set; }
        public Nullable<bool> deal { get; set; }
        public Nullable<bool> done { get; set; }
        public string quoteno { get; set; }
    }
}
