//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiuQinSys.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartPrepareOrderSub
    {
        public long id { get; set; }
        public string quoteOrderNo { get; set; }
        public Nullable<byte> orderNo { get; set; }
        public string productId { get; set; }
        public string productName { get; set; }
        public Nullable<short> count { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
