//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiuQinSys.Modle
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public string id { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public string type { get; set; }
        public string unit { get; set; }
        public Nullable<int> price { get; set; }
        public string descript { get; set; }
        public Nullable<int> inventory { get; set; }
        public Nullable<int> buypoint { get; set; }
        public Nullable<byte> buyday { get; set; }
        public short stock { get; set; }
    }
}
