//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiuQinSys.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteOrderSub
    {
        public string no { get; set; }
        public byte orderno { get; set; }
        public string productID { get; set; }
        public string productName { get; set; }
        public Nullable<short> count { get; set; }
        public Nullable<int> pice { get; set; }
        public string descript { get; set; }
        public Nullable<bool> isDisplayNameAndDescript { get; set; }
    }
}
